"""updated the user table

Revision ID: a7e8970a2b78
Revises: 418b2dfe6c82
Create Date: 2026-09-12 15:26:24.649410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7e8970a2b78'
down_revision: Union[str, Sequence[str], None] = '418b2dfe6c82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.Unicode(length=30), nullable=True))
    op.add_column('users', sa.Column('first_name', sa.Unicode(length=255), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.Unicode(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
